#!/bin/bash
#
# weather-power-saver
#
# This script is executed by power-saver.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#

# Weather Station power saving...
# Set ENABLE to "true" to let the script run at boot time.
ENABLE="true"
NAME=rtcwake
WAKETIME=20
SLEEPTIME=300
DAYTIME=06:30
NIGHTTIME=19:00
NSLEEPTIME=1800
TIMEOUT=60
SETTIME="false"
RUN=/usr/sbin/$NAME
RUNOPTS="-m standby -s"
INA219=/home/debian/ina219-tool

# if not enabled then exit gracefully
[ "$ENABLE" = "true" ] || exit 0

# Exit if the package is not installed
[ -x "$RUN" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

wait_until_online() {
    echo
    # Wait upto 60 seconds for online network
    while [ $TIMEOUT -gt 0 ]; do 
        echo -ne "Waiting for network... $TIMEOUT (seconds)\r";
        sleep 1;
        ping -c1 www.google.com &> /dev/null;
        if [ $? -eq 0 ]; then 
            let TIMEOUT=0
        else
            let TIMEOUT--
        fi;
    done
    echo
}

while true; do
    sleep $WAKETIME
    service weewx stop
    yes | wee_device --clear

    NOW=$(date "+%s")
    if [ "$NOW" -gt $(date "+%s" -d $DAYTIME) ] && [ "$NOW" -lt $(date "+%s" -d $NIGHTTIME) ]
    then
        $RUN $RUNOPTS $SLEEPTIME
    else
        $RUN $RUNOPTS $NSLEEPTIME
    fi
    
    wait_until_online
    service weewx start
    
    # Optional webcam (daytime only)
    if [ "$NOW" -gt $(date "+%s" -d $DAYTIME) ] && [ "$NOW" -lt $(date "+%s" -d $NIGHTTIME) ]
    then
        if [ -f "$INA219" ] && [ -x "$INA219" ]
        then
            BATTERY=$($INA219 -a -d /dev/i2c-2 40)
        fi

        fswebcam -r 1280x720 -S 100 --timestamp "%H:%M:%S (%Z) %a %d %B %Y" -d /dev/video0 --jpeg 75 --title "NHPC webcam - East Hill" --subtitle "$BATTERY"  /tmp/image.jpg --exec /etc/upload.sh
    fi
    
done

exit 0
